### ISSUE TITLE
Add Procfile management tool for application

### ISSUE THREAD

**Issue by gutakk** [nimblehq/gin-templates#21]
## Why
As having more than one process is very common, Procfile is preferred tool to manage more than one process application.

## Acceptance Criteria
- Add [forego](https://github.com/ddollar/forego) or [goreman](https://github.com/mattn/goreman).
 
## Who Benefits?
Developers

**Comment by malparty** [comment]
Forego added by @hoangmirs in #50 (PR #62 ) ;-)
