### ISSUE TITLE
RFC: Versioning schema migration tools doesn't support out-of-order migration

### ISSUE THREAD

**Issue by gutakk** [nimblehq/gin-templates#22]
## Why
As this template decide to use `GORM` as an ORM but GORM doesn't provide versioning schema migration. With described issue I found two widely use tools for versioning schema migration.
1. [Go Migrate](https://github.com/golang-migrate/migrate)
2. [Goose](https://github.com/pressly/goose)

They both have CLI with almost the same functionalities.

But both of them also have an issue that I concern. It is both of them don't support migrate the older migration file. Thinking of if more than one developers working on the same project and they are working with migration. The first developer create migration before second developer but second developer merge the code before first developer then the migration will be out-of-order. Both of these tools don’t warn anything about this when you run the migration and I think this could lead to something critical in the future.

Do I need to concern what I just raised?

**Note**
Goose recommend to use Hybrid versioning. More information [here](https://github.com/pressly/goose#hybrid-versioning)

**Comment by olivierobert** [comment]
It's a valid concern to raise that should go into the Wiki to document this template. In terms of implementation, Go Migrate seems more widely used (and also not being a fork of Bitbucket helps 💯 ).

In terms of working the issue you are raising, there are several options:
- Add a codebase test which be executed on the CI and fail the test suite if a new migration added in a PR is older than the latest migration on the destination branch.
- Track migration executed via the DB as done on Rails in the versions table.
- Crete a script to rename migration as sequential as proposed by Goose. 
But that goes beyond the scope of this template. 

So I recommend to document the issue in the wiki and then work on a solution in a separate task post-1.0.0.

**Comment by gutakk** [comment]
> It's a valid concern to raise that should go into the Wiki to document this template. In terms of implementation, Go Migrate seems more widely used (and also not being a fork of Bitbucket helps 💯 ).
> 
> In terms of working the issue you are raising, there are several options:
> 
> * Add a codebase test which be executed on the CI and fail the test suite if a new migration added in a PR is older than the latest migration on the destination branch.
> * Track migration executed via the DB as done on Rails in the versions table.
> * Crete a script to rename migration as sequential as proposed by Goose.
>   But that goes beyond the scope of this template.
> 
> So I recommend to document the issue in the wiki and then work on a solution in a separate task post-1.0.0.

@olivierobert 
I just found 3 big differences between Goose and Go Migrate
1. Go Migrate store only latest migrated migration in the database while Goose store every migrated migrations.
2. Go Migrate does not have rollback to specific migration feature. They have only `down` feature which is rollback to the first migration. On the other hand, Goose does have rollback feature. You can choose how many migration to rollback or rollback the whole thing.
3. Go Migrate does not allow you to run migrate again if the migration failed before. For example you write the wrong sql syntax and run the migration, Go Migrate will print the error for you and after you fix the sql syntax and run the migration again, Go Migrate will raise an error `Dirty database version X. Fix and force version`. You need to run the Go Migrate `force` script to force the schema tracking table to track last version of migration and you will be able to run the migration again (for more information [click](https://github.com/golang-migrate/migrate/issues/282#issuecomment-530732246)). While Goose doesn't have to do this.

With described above, I'm not sure if we should use Go Migrate.
What do you think?

**Comment by olivierobert** [comment]
After so many compelling arguments against Go Migrate, Goose does seem a better choice. 

I have checked a few awesome list (like [this one](https://github.com/avelino/awesome-go) and [this one](https://github.com/uhub/awesome-go)) without finding a better alternative.

**Comment by gutakk** [comment]
> It's a valid concern to raise that should go into the Wiki to document this template. In terms of implementation, Go Migrate seems more widely used (and also not being a fork of Bitbucket helps 💯 ).
> 
> In terms of working the issue you are raising, there are several options:
> 
> * Add a codebase test which be executed on the CI and fail the test suite if a new migration added in a PR is older than the latest migration on the destination branch.
> * Track migration executed via the DB as done on Rails in the versions table.
> * Crete a script to rename migration as sequential as proposed by Goose.
>   But that goes beyond the scope of this template.
> 
> So I recommend to document the issue in the wiki and then work on a solution in a separate task post-1.0.0.

Create two new issues to solve this https://github.com/nimblehq/gin-templates/issues/30 and https://github.com/nimblehq/gin-templates/issues/29
