### ISSUE TITLE
Update step create env description in test.yml

### ISSUE THREAD

**Issue by byhbt** [nimblehq/gin-templates#40]
## Why

Update the description for steps in  `.github/workflows/test.yml` to make it more expressive. 

For example:

```yaml
- name: Create ENV file
```

To

```yaml
- name: Create .env file
```
 
## Who Benefits?

Developers

**Comment by junan** [comment]
@byhbt Since this issue you submitted and assigned to you long ago. Can you please work on it when you can?

**Comment by carryall** [comment]
Closed this issue as the PR #42 is already merged
