### ISSUE TITLE
Add Tailwind Add-on

### ISSUE THREAD

**Issue by gutakk** [nimblehq/gin-templates#59]
## Why

As we will add the web variant to Gin template, CSS framework is nice to have to reduce set up steps for the developer
 
## Acceptance Criteria

- Create Tailwind addon
- Include unit test

**Comment by malparty** [comment]
@gutakk @hoangmirs 
What setup of Tailwind would you like?

A. Minimal (just setup into postcss and add the vendor imports in application.scss:
```scss
// Vendors
@tailwind base;
@tailwind components;
@tailwind utilities;
```
> Already done & working on my local machine ;-) 

B. Add purge optimizations for Production (as recommended [here](https://tailwindcss.com/docs/optimizing-for-production))

C. Any other specific configuration to be included?
