### ISSUE TITLE
Fix: golangci-lint-action failing in the CI

### ISSUE THREAD

**Issue by junan** [nimblehq/gin-templates#78]
## Issue

Currently, [golangci-lint-action ](https://github.com/nimblehq/gin-templates/runs/6170339399?check_suite_focus=true) fails in the CI when creating a new PR(but passes in local), even without significant changes

## Expected

CI should be passed

## Steps to reproduce

Just create a PR with any changes

**Comment by hoangmirs** [comment]
I created a PR to fix it here:
https://github.com/nimblehq/gin-templates/pull/79
